import Head from 'next/head'
import { FC } from 'react'

import client from '../src/libs/apollo'
import GET_ALL_PROGRAMS from '../src/queries/getAllPrograms'
import ProgramSlider, { SliderProps } from '../src/components/ProgramSlider/ProgramSlider'

type HomeType = {
  program: SliderProps
}

const Home: FC<HomeType> = ({ program }) => {
  return (
    <div>
      <Head>
        <title>TF1 Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ProgramSlider {...program} />
      </main>
    </div>
  )
}

export default Home

export async function getServerSideProps() {
  const { data } = await client.query({
    query: GET_ALL_PROGRAMS,
    variables: { limit: 20 },
  })

  return {
    props: {
      program: data?.program,
    },
  }
}
